### ISSUE TITLE
twitter cookie is not set

### ISSUE THREAD

**Issue by fattouchsquall** [FriendsOfSymfony/FOSTwitterBundle#19]
Hi,

when i try to login into my application with twitter and combine this with custom user provider , i'd this error "twitter_anywhere_identity" is not sent!! wich means that it throws the exception in where identity is empty !! 
For information, i use the connexion with a callbackURL for localhost.

Anyone have idea how to resolve this please!

**Comment by stof** [comment]
Are you using Twitter Anywhere or the standard Twitter login ? The bundle provides both.

**Comment by fattouchsquall** [comment]
i use Twitter anywhere, i activated it in my firewall config.

**Comment by fattouchsquall** [comment]
Hi,
i resolved the problem and i have now the authentification with TwitterBundle with a provider. The solution was not to use Twitter anywhere but the standard Twitter login. This is my security config if it will help to combine the three providers in the same application:

``` yaml
providers:
        chain_provider: 
            providers: [fos_userbundle, user_bundle.facebook.provider, user_bundle.twitter.provider ] 
        fos_userbundle:
            id: fos_user.user_manager
        user_bundle.facebook.provider:
            id: user_bundle.facebook.authentication
        user_bundle.twitter.provider:
            id: user_bundle.twitter.authentication
public:
            pattern:   /.*
            fos_facebook:
                app_url: "https://www.facebook.com/apps/application.php?id=271523619566485"
                server_url: "http://localhost/abalista2/web/app_dev.php/"
                login_path: /user/login
                check_path: /user/facebook/fb_login_check
                provider: user_bundle.facebook.provider
                default_target_path: /contact
            fos_twitter:
                login_path: /user/login
                check_path: /user/twitter/tw_login_check
                provider: user_bundle.twitter.provider
                default_target_path: /contact
            form_login:
                provider: fos_userbundle
                login_path: /user/login
                use_forward:    false
                check_path: /user/login_check
```
