### ISSUE TITLE
Error with symfony 2.1

### ISSUE THREAD

**Issue by oscargala** [FriendsOfSymfony/FOSTwitterBundle#23]
Hi,

I am trying to implement the FOSTwitterBundle and I followed the readme instructions. I'm using the Symfony 2.1 master branch and I get the following error:

User provider "FOS\TwitterBundle\Security\Authentication\Provider\TwitterProvider" must implement "Symfony\Component\Security\Core\User\UserProviderInterface". 

I do see the "Uses Symfony\Component\Security\Core\User\UserProviderInterface"  line in TwitterProvider.php.
Any idea what could be going wrong?
Thank you.

**Comment by stof** [comment]
TwitterProvider is an authentication provider, not a user provider. I think you misused the bundle in your SecurityBundle configuration. Can you paste it ?

**Comment by stof** [comment]
closing as there is no answer from the reporter

**Comment by oscargala** [comment]
My apologies, I missed your initial reply. You were correct that I misused it. At the time I did not have a clear understanding of how the symfony security worked.

**Comment by casoetan** [comment]
Hello, now I seem to have that same challenge. How did you solve it jinfolic? I want to use both twitter and facebook (fos bundles) authentication with the fosuserbundle

**Comment by oscargala** [comment]
Sorry casoetan...I can't remember what I exactly did. In the end I actually needed a custom oauth1a provider, so I made that myself.

**Comment by gicush0r** [comment]
Hi everybody,

I have same problem, and I don't know as resolve it. I use FOSFacebookBundle and it work very well, and I use FOSUserBundle for authentication. Anyone can help me ?

regards

**Comment by gicush0r** [comment]
Hi,

I solved it, the problem is I forget change in the security.yml secuity.firewalls.public anonymous: true to anonymous: ~ .

this is all.

regards

**Comment by elyobo** [comment]
Same problem here, cutting and pasting the configuration exactly as desccribed in in the docs triggers the error.  Changing security.firewalls.public anonymous to ~ makes no difference, but removing the providers.fos_twitter entry does make the error go away (whether it breaks everything else remains to be seen at the moment).

**Comment by ec-gsitu** [comment]
Hey I'm currently using the same FOS Twitter bundle and I have this error

User provider "FOS\TwitterBundle\Security\Authentication\Provider\TwitterProvider" must implement "Symfony\Component\Security\Core\User\UserProviderInterface".

I've also tried settings "anonymous = ~'" and that did not work either.

If I remove the fos_twittter and id lines from the providers then I do not get this error. This is my security.yml. It's the same as the authors set it up on their instructions/readme.

``` yaml
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_twitter:
            id: fos_twitter.auth

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo

        secured:
            pattern: /secured/.*
            fos_twitter: true        

        public:
            pattern: /.*
            anonymous: true
            fos_twitter: true
            logout: true


            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: /.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```
