### ISSUE TITLE
Fatal Error when user login twitter account and redirected back to website

### ISSUE THREAD

**Issue by asingh8c** [FriendsOfSymfony/FOSTwitterBundle#29]
Receiving following error when afterlogin twitter account:
Fatal error: Call to undefined method TwitterOAuth::setOAuthToken() in C:\wamp\www\Symfony\vendor\bundles\FOS\TwitterBundle\Services\Twitter.php on line 70

My firewall setting is:

```
    secured_area:
        fos_facebook:
            app_url: "https://apps.facebook.com/ymmudab"
            server_url: "http://localhost:78/Symfony/web/app_dev.php/"
            login_path: facebook_login
            check_path: facebook_login_check
            provider: my_fos_facebook_provider
            default_target_path: welcome
        fos_twitter:
            login_path: twitter_login
            check_path: twitter_login_check
            default_target_path: welcome
            provider: my_fos_twitter_provider
        form_login:
            login_path: twitter_login
            check_path: twitter_login_check
            provider: user_db
            default_target_path: welcome
        logout:
            path:   logout
            target: /
            handlers: ["fos_facebook.logout_handler"]
        anonymous: ~
```

I am using Abrahma's twitter library.Please advice.
