### ISSUE TITLE
Save user information in database using FOSTwitterBundle

### ISSUE THREAD

**Issue by naqac** [FriendsOfSymfony/FOSTwitterBundle#57]
I installed FOSTwitterBundle using your tutorial here ,but I have an issue about how to save informations in my database of every user logged using his twitter account ?

I have this error :  
_ErrorException: Catchable Fatal Error: Argument 2 passed to Skeleton\PanelBundle\Security\User\Provider\TwitterUserProvider::__construct() must be an instance of FOS\UserBundle\Entity\UserManager, instance of FOS\UserBundle\Doctrine\UserManager given, called in /var/www/skeleton/app/cache/dev/appDevDebugProjectContainer.php on line 1678 and defined in /var/www/skeleton/src/Skeleton/PanelBundle/Security/User/Provider/TwitterUserProvider.php line 34_

here is my config.yml : 

*services:
    my.twitter.user:
        class: Skeleton\PanelBundle\Security\User\Provider\TwitterUserProvider
        arguments:
            twitter_oauth: "@fos_twitter.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            session: "@session" *

and security.yml :

*security:
encoders:
    Symfony\Component\Security\Core\User\User: plaintext

role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

providers:

```
my_fos_twitter_provider:
    id: my.twitter.user 
```

firewalls:
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

```
public:
    pattern:  /
    fos_twitter:
        login_path: /twitter/login
        check_path: /twitter/login_check
        default_target_path: /
        provider: my_fos_twitter_provider

    anonymous: ~* 
```

I spend almost all day but no solution!
