### ISSUE TITLE
Logout does not logout

### ISSUE THREAD

**Issue by rdohms** [FriendsOfSymfony/FOSTwitterBundle#8]
Accessing /logout is not causing the token to be removed, when redirected back i still hold the same token with my twitter UID

This is my config

```
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    providers:
        fos_twitter:
            id: phpsp.twitter.auth

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured:
            pattern:    ^/
            anonymous: ~
            fos_twitter: true
            logout: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

i wrote a wrapper to the provider, which basically adds a UserProvider, but it was still not working before this. Also i can't seem to make my custom user provider talk to your service.
