### ISSUE TITLE
Impossible to Write Extension to fos_twitter.auth

### ISSUE THREAD

**Issue by rdohms** [FriendsOfSymfony/FOSTwitterBundle#9]
I might be going at this wrong, so please help me out if i'm completely lost.

I wanted to pass on a custom UserProvider to the fos_twitter.auth service (the 3rd parameter). I found no way to do this using the configuration, so  wrote a custom service which basically extends the TwitterProvider and instantiates a new UserProvider and passes it on to the FOS TwitterProvider constructor.

I altered the security config to :

```
providers:
     twitter:
         id: phpsp.twitter.auth
```

Problem is the Factory forces the use of the .auth service on line 76 in the createAuthProvider function. This is because this is hardcoded to point to fos_twitter.auth. 

This caused me to have 2 instances of the Provider and the wrong one to be used on authentication. Changing that line 76 to point to my service did the trick, so i wonder if this should read form config instead of hardcoding itself? or maybe i just went about everything wrong.

**Comment by arghav** [comment]
It should work fine if you add `provider` for `fos_twitter` in your firewalls config. Something like...

```
main:
    pattern: ^/
    fos_twitter:
        provider: twitter
    anonymous: true
    logout: ~
```

**Comment by stof** [comment]
@rdohms you confused 2 different things: the authentication provider used by the firewall (which is `fos_twitter.auth`), and the user provider. The `providers` section of the configuration is about user providers.

And the Twitter authentication provider already supports (optionally) using a user provider. You simply need to configure it in your security config as @kertz said.

``` yaml
# app/config/security.yml

security:
    provider:
        my_provider:
            # using the entity provider here but could be any provider
            entity: { class: "Acme\DemoBundle\Entity\User", property: "twitterId" }
    firewalls:
        main:
            fos_twitter:
                provider: my_provider
```
